version: '3.7'
services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-q", "-b", "golang-books", "-U", "postgres"]
      timeout: 20s
      interval: 10s
      retries: 5
  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

networks:
    backend:
      driver: bridge